### ISSUE TITLE
Для чего нужен открытый user_service?

### ISSUE THREAD

**Issue by hawkkiller** [theartofdevel/notes_system#5]
Привет, я заметил что тут реализован апи гейтвей, но зачем user_service открыт для запросов? Выходит, что любой может достучаться до него без токена и сделать что-либо плохое :) 
@theartofdevel

**Comment by ghost** [comment]
@hawkkiller Думаю это всё будет закрываться на уровне сети.

**Comment by o1o1o3** [comment]
@hawkkiller наружу торчит только те сервисы, которым вы это позволите =) в моем случае это будет gateway, а user-service и все остальные сервисы будут закрыты как правильно отметил @vitalii-pokrivchak на уровне сети.
